---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "[%(name)s.%(funcName)s][%(levelname)s] -- %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: CRITICAL
        formatter: simple
        stream: ext://sys.stdout
    smoresHandle:
        class: smores.utility.smoreslog.SmoresFileLog
        level: WARN
        formatter: simple
        name: ../smores/logs/smores.log
        mode: a
        maxsize: 0
        backup: 1
    APIHandle:
        class: smores.utility.smoreslog.SmoresFileLog
        level: INFO
        formatter: simple
        name: ../smores/logs/API.log
        mode: a
        maxsize: 0
        backup: 1
    errorsHandle:
        class: smores.utility.smoreslog.SmoresFileLog
        level: ERROR
        formatter: simple
        name: ../smores/logs/errors.log
        mode: a
        maxsize: 0
        backup: 1
loggers:
    smores.processes:
        level: DEBUG
        handlers: [smoresHandle, errorsHandle, console]
        propagate: False
    smores.medication:
        level: DEBUG
        handlers: [smoresHandle, errorsHandle, console]
        propagate: False
    smores.medicationdictionary:
        level: DEBUG
        handlers: [smoresHandle, errorsHandle, console]
        propagate: False
    smores.medkit:
        level: DEBUG
        handlers: [smoresHandle, errorsHandle, console]
        propagate: False
    smores.api:
        level: DEBUG
        handlers: [APIHandle, errorsHandle, console]
        propagate: False
root:
    level: INFO
    handlers: [console]
