---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(name)-20s%(levelname)-8s%(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    main:
        class: smores.smoreslog.MultiProcessingLog
        level: DEBUG
        formatter: simple
        name: ../smores/logs/main.log
        mode: w
        maxsize: 1024
        rotate: 0
    smoresHandle:
        class: smores.smoreslog.MultiProcessingLog
        level: DEBUG
        formatter: simple
        name: ../smores/logs/smores.log
        mode: w
        maxsize: 1024
        rotate: 0
    rxnormHandle:
        class: smores.smoreslog.MultiProcessingLog
        level: DEBUG
        formatter: simple
        name: ../smores/logs/rxnorm.log
        mode: w
        maxsize: 1024
        rotate: 0
loggers:
    smores:
        level: DEBUG
        handlers: [smoresHandle, main, console]
        propagate: no
    rxnorm:
        level: DEBUG
        handlers: [rxnormHandle, main, console]
        propagate: no
root:
    level: INFO
    handlers: [console,main]
